Repository rt-net/raspimouse_description, pull requests merged in 2020-02, with the labels that each got.

#5 remove unused comments from CMakelists.txt
  CMakeLists.txt
Labels: refactor

#6 Update README.md
  README.md
Labels: documentation

#9 Migrate package.xml to format2
  package.xml
Labels: enhancement
